#!/usr/bin/env bash

set -e
export GROUPAROO_TELEMETRY_ENABLED=false

cd "`dirname "$0"`/.."

printf "*** starting server ***\r\n"
npm run start &

sleep 30

printf "*** checking status ***\r\n"
curl http://localhost:3000/api/v1/status/public

printf "It worked!\r\n"
pkill -f dist/grouparoo
wait

printf "Done!\r\n"
