name: publish

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.BOT_GITHUB_PAT }}
      - name: store-core-version
        run: echo CORE_VERSION=`cat package.json | jq -r '.dependencies."@grouparoo/core"'` >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: grouparoo/omnibus:latest, grouparoo/omnibus:v${{ env.CORE_VERSION }}
          secrets: |
            "npmrc=//registry.npmjs.org/:_authToken=${{ secrets.BOT_NPM_TOKEN }}"
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  notify-terraform:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'grouparoo/omnibus' }}
    needs: publish
    steps:
      - name: Notify
        run: >-
          curl
          -X POST
          -u "${{secrets.BOT_GITHUB_USERNAME}}:${{secrets.BOT_GITHUB_PAT}}"
          -H "Accept: application/vnd.github.everest-preview+json"
          -H "Content-Type: application/json"
          https://api.github.com/repos/grouparoo/grouparoo-infra-apps/actions/workflows/update-docker-versions.yml/dispatches
          --data '{"ref": "main"}'
