name: update

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: cp .env.example .env
      - name: configure .npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.BOT_NPM_TOKEN }}" > .npmrc
      - name: check npm user
        run: npm whoami
      - run: npm install
      - run: sudo npm install -g npm-check-updates
      - run: npm-check-updates -u --target greatest
      - run: npm install
      - name: store-core-version
        run: echo CORE_VERSION=`cat package.json | jq -r '.dependencies."@grouparoo/core"'` >> $GITHUB_ENV
      - name: Create commits
        run: |
          git config user.name 'Grouparoo Bot'
          git config user.email 'hello@grouparoo.com'
          git commit -am "Updating Packages to v${{ env.CORE_VERSION }}"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Updating Grouparoo to v${{ env.CORE_VERSION }}"
          body: "Grouparoo v${{ env.CORE_VERSION }} is now available."
